/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bible3;

/**
 *
 * @author mark
 */
public interface BooksTitle {

    String[] OLD_TESTAMENT = {
        "Genesis",
        "Exodus",
        "Leviticus",
        "Numbers",
        "Deuteronomy",
        "Joshua",
        "Judges",
        "Ruth",
        "1 Samuel",
        "2 Samuel",
        "1 Kings",
        "2 Kings",
        "1 Chronicles",
        "2 Chronicles",
        "Ezra",
        "Nehemiah",
        "Esther",
        "Job",
        "Psalms",
        "Proverbs",
        "Ecclesiastes",
        "Song of Solomon",
        "Isaiah",
        "Jeremiah",
        "Lamentations",
        "Ezekiel",
        "Daniel",
        "Hosea",
        "Joel",
        "Amos",
        "Obadiah",
        "Jonah",
        "Micah",
        "Nahum",
        "Habakkuk",
        "Zephaniah",
        "Haggai",
        "Zechariah",
        "Malachi"

    };

    String[] OLD_TESTAMENT_CHINESE = {
        "創世紀",
        "出埃及記",
        "利未記",
        "民數記",
        "申命記",
        "約書亞記",
        "士師記",
        "路得記",
        "撒母耳記上",
        "撒母耳記下",
        "列王記上",
        "列王記下",
        "歷代志上",
        "歷代志下",
        "以斯拉記",
        "尼希米記",
        "以斯帖記",
        "約伯記",
        "詩篇",
        "箴言",
        "傳道書",
        "雅歌",
        "以賽亞書",
        "耶利米書",
        "耶利米哀歌",
        "以西結書",
        "但以理書",
        "何西阿書",
        "約珥書",
        "阿摩司書",
        "俄巴底亞書",
        "約拿書",
        "彌迦書",
        "那鴻書",
        "哈巴谷書",
        "西番雅書",
        "哈該書",
        "撒迦利亞",
        "瑪拉基書"
    };

    String[] OLD_TESTAMENT_CHINESE_SHORT = {
        "創",
        "出",
        "利",
        "民",
        "申",
        "書",
        "士",
        "路",
        "撒上",
        "撒下",
        "王上",
        "王下",
        "代上",
        "代下",
        "拉",
        "尼",
        "斯",
        "伯",
        "詩",
        "箴",
        "傳",
        "歌",
        "賽",
        "耶",
        "哀",
        "結",
        "但",
        "何",
        "珥",
        "摩",
        "俄",
        "拿",
        "彌",
        "鴻",
        "哈",
        "番",
        "該",
        "亞",
        "瑪"
    };

    String[] NEW_TESTAMENT = {
        "Matthew",
        "Mark",
        "Luke",
        "John",
        "Acts",
        
        "Romans",
        "1 Corinthians",
        "2 Corinthians",
       
        "Galatians",
        "Ephesians",
        "Philippians",
        "Colossians",
      
        "1 Thessalonians",
        "2 Thessalonians",
        "1 Timothy",
        "2 Timothy",
        "Titus",
        "Philemon",
        "Hebrews",
        "James",
        "1 Peter",
        "2 Peter",
        "1 John",
        "2 John",
        "3 John",
        "Jude",
        "Revelation"

    };

    String[] NEW_TESTAMENT_CHINESE = {
        "馬太福音",
        "馬可福音",
        "路加福音",
        "約翰福音",
        "使徒行傳",
        "羅馬書",
        "哥林多前書",
        "哥林多後書",
        "加拉太書",
        "以弗所書",
        "腓立比書",
        "歌羅西書",
        "帖撒羅尼迦前書",
        "帖撒羅尼迦後書",
        "提摩太前書",
        "提摩太後書",
        "提多書",
        "腓利門書",
        "希伯來書",
        "雅各書",
        "彼得前書",
        "彼得後書",
        "約翰一書",
        "約翰二書",
        "約翰三書",
        "猶大書",
        "啟示錄"
    };
    
    String[] NEW_TESTAMENT_CHINESE_SHORT = {
        "太",
        "可",
        "路",
        "約",
        "徒",
        "羅",
        "林前",
        "林後",
        "加",
        "弗",
        "腓",
        "西",
        "帖前",
        "帖後",
        "提前",
        "提後",
        "多",
        "門",
        "來",
        "雅",
        "彼前",
        "彼後",
        "約一",
        "約二",
        "約三",
        "猶",
        "啟"
    };
    
    
}
